### ISSUE TITLE
IMU to default

### ISSUE THREAD

**Issue by martimorta-at-work** [i3drobotics/i3dr_phobos_nuclear-ros#1]
Hi, 
IMU should default to false since there is no IMU currently.
https://github.com/i3drobotics/i3dr_phobos_nuclear-ros/blob/980e55b9d6364a20d82d6d26193d265cabb14f99/launch/phobos_nuclear.launch#L21
Thanks!

**Comment by ghost** [comment]
Happy to make the change. We are currently testing Phobos in the lab that does have an IMU but I agree that the repo should reflect what is in public use.
