### ISSUE TITLE
Argument doesn't exist in stereo_matcher.launch

### ISSUE THREAD

**Issue by martimorta-at-work** [i3drobotics/i3dr_phobos_nuclear-ros#2]
Hi this argument doesn't exist in stereo_matcher.launch (at least in the master branch)
https://github.com/i3drobotics/i3dr_phobos_nuclear-ros/blob/0c956b8390cc79a05cdb8df611007b253d626158/launch/phobos_nuclear.launch#L92
Cheers

**Comment by ghost** [comment]
This is a holdover from an old stereo_matcher launcher. I must have missed it. It is now removed.

**Comment by martimorta-at-work** [comment]
Sorry Ben, this is also deprecated 
https://github.com/i3drobotics/i3dr_phobos_nuclear-ros/blob/0c956b8390cc79a05cdb8df611007b253d626158/launch/phobos_nuclear.launch#L78

**Comment by ghost** [comment]
Thanks, Marti. It looks like I only tested the changes to i3dr_stereo_camera on i3dr_phobos and i3dr_deimos. I am busy this week but I will make sure to test the i3dr_phobos_nuclear package early next week.

**Comment by ghost** [comment]
Actually now I think of it, I think I did that as I integrated the changes from phobos-nuclear into the phobos package. If it doesn't completely ruin the launchers you currently have try moving to using the i3dr_phobos package instead.

**Comment by ghost** [comment]
I just checked and the packages were combined in this [commit](https://github.com/i3drobotics/i3dr_phobos-ros/commit/9136f59a9a0c419cb882cd25873f2c7b06698969).
